project:
  type: website
  output-dir: docs

website:
  title: "Tributes to Professor Margaret Robinson"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css